services:
  wissellijst:
    build: .
    container_name: wissellijst-v2
    env_file:
      - .env
    volumes:
      - wissellijst-data:/app/data
    ports:
      - "9090:5000"
    restart: unless-stopped

volumes:
  wissellijst-data:
